### ISSUE TITLE
Error moving file to archive

### ISSUE THREAD

**Issue by dhyeem** [slashdoom/cdr_parser#1]
Dear, the Script you created is amazing, it work for a while till it reach some files i will put to you one file that have an issue below, this is the error i'm facing: 

```
2016-07-13 21:11:11,908 - {u'_type': u'cdr-cucm', u'created': True, u'_shards': {u'successful': 1, u'failed': 0, u'total': 2}, u'_version': 1, u'_index': u'cdr-%s', u'_id': u'AVXldJmcrUyahp0h5Gdu'}
2016-07-13 21:11:11,908 - src_file = /home/dhyeem/logs/cdr_StandAloneCluster_01_201511010648_9357
2016-07-13 21:11:11,908 - dest_file = /home/dhyeem/logs/archive/cdr_StandAloneCluster_01_201511010648_9357
2016-07-13 21:11:11,908 - es_type = cdr-cucm
2016-07-13 21:11:11,908 - Error moving file to archive.
Traceback (most recent call last):
  File "/usr/lib/python2.7/logging/__init__.py", line 885, in emit
    self.flush()
  File "/usr/lib/python2.7/logging/__init__.py", line 845, in flush
    self.stream.flush()
IOError: [Errno 9] Bad file descriptor
Logged from file mod_cdr_main.py, line 51
2016-07-13 21:11:12,017 - {u'_type': u'cdr-cucm', u'created': True, u'_shards': {u'successful': 1, u'failed': 0, u'total': 2}, u'_version': 1, u'_index': u'cdr-%s', u'_id': u'AVXldJoNrUyahp0h5Gdv'}
2016-07-13 21:11:12,017 - src_file = /home/dhyeem/logs/cdr_StandAloneCluster_01_201511010546_9351
2016-07-13 21:11:12,017 - dest_file = /home/dhyeem/logs/archive/cdr_StandAloneCluster_01_201511010546_9351
2016-07-13 21:11:12,017 - es_type = cdr-cucm
2016-07-13 21:11:12,017 - Error moving file to archive.
Traceback (most recent call last):
  File "/usr/lib/python2.7/logging/__init__.py", line 885, in emit
    self.flush()
  File "/usr/lib/python2.7/logging/__init__.py", line 845, in flush
    self.stream.flush()
IOError: [Errno 9] Bad file descriptor
Logged from file mod_cdr_main.py, line 51
Terminating on signal 15
```

this is the document i'm trying to parse: 

`"cdrRecordType","globalCallID_callManagerId","globalCallID_callId","origLegCallIdentifier","dateTimeOrigination","origNodeId","origSpan","origIpAddr","callingPartyNumber","callingPartyUnicodeLoginUserID","origCause_location","origCause_value","origPrecedenceLevel","origMediaTransportAddress_IP","origMediaTransportAddress_Port","origMediaCap_payloadCapability","origMediaCap_maxFramesPerPacket","origMediaCap_g723BitRate","origVideoCap_Codec","origVideoCap_Bandwidth","origVideoCap_Resolution","origVideoTransportAddress_IP","origVideoTransportAddress_Port","origRSVPAudioStat","origRSVPVideoStat","destLegIdentifier","destNodeId","destSpan","destIpAddr","originalCalledPartyNumber","finalCalledPartyNumber","finalCalledPartyUnicodeLoginUserID","destCause_location","destCause_value","destPrecedenceLevel","destMediaTransportAddress_IP","destMediaTransportAddress_Port","destMediaCap_payloadCapability","destMediaCap_maxFramesPerPacket","destMediaCap_g723BitRate","destVideoCap_Codec","destVideoCap_Bandwidth","destVideoCap_Resolution","destVideoTransportAddress_IP","destVideoTransportAddress_Port","destRSVPAudioStat","destRSVPVideoStat","dateTimeConnect","dateTimeDisconnect","lastRedirectDn","pkid","originalCalledPartyNumberPartition","callingPartyNumberPartition","finalCalledPartyNumberPartition","lastRedirectDnPartition","duration","origDeviceName","destDeviceName","origCallTerminationOnBehalfOf","destCallTerminationOnBehalfOf","origCalledPartyRedirectOnBehalfOf","lastRedirectRedirectOnBehalfOf","origCalledPartyRedirectReason","lastRedirectRedirectReason","destConversationId","globalCallId_ClusterID","joinOnBehalfOf","comment","authCodeDescription","authorizationLevel","clientMatterCode","origDTMFMethod","destDTMFMethod","callSecuredStatus","origConversationId","origMediaCap_Bandwidth","destMediaCap_Bandwidth","authorizationCodeValue","outpulsedCallingPartyNumber","outpulsedCalledPartyNumber","origIpv4v6Addr","destIpv4v6Addr","origVideoCap_Codec_Channel2","origVideoCap_Bandwidth_Channel2","origVideoCap_Resolution_Channel2","origVideoTransportAddress_IP_Channel2","origVideoTransportAddress_Port_Channel2","origVideoChannel_Role_Channel2","destVideoCap_Codec_Channel2","destVideoCap_Bandwidth_Channel2","destVideoCap_Resolution_Channel2","destVideoTransportAddress_IP_Channel2","destVideoTransportAddress_Port_Channel2","destVideoChannel_Role_Channel2","IncomingProtocolID","IncomingProtocolCallRef","OutgoingProtocolID","OutgoingProtocolCallRef","currentRoutingReason","origRoutingReason","lastRedirectingRoutingReason","huntPilotPartition","huntPilotDN","calledPartyPatternUsage","IncomingICID","IncomingOrigIOI","IncomingTermIOI","OutgoingICID","OutgoingOrigIOI","OutgoingTermIOI","outpulsedOriginalCalledPartyNumber","outpulsedLastRedirectingNumber","wasCallQueued","totalWaitTimeInQueue","callingPartyNumber_uri","originalCalledPartyNumber_uri","finalCalledPartyNumber_uri","lastRedirectDn_uri","mobileCallingPartyNumber","finalMobileCalledPartyNumber","origMobileDeviceName","destMobileDeviceName","origMobileCallDuration","destMobileCallDuration","mobileCallType","originalCalledPartyPattern","finalCalledPartyPattern","lastRedirectingPartyPattern","huntPilotPattern"
INTEGER,INTEGER,INTEGER,INTEGER,INTEGER,INTEGER,INTEGER,INTEGER,VARCHAR(50),VARCHAR(128),INTEGER,INTEGER,INTEGER,INTEGER,INTEGER,INTEGER,INTEGER,INTEGER,INTEGER,INTEGER,INTEGER,INTEGER,INTEGER,VARCHAR(64),VARCHAR(64),INTEGER,INTEGER,INTEGER,INTEGER,VARCHAR(50),VARCHAR(50),VARCHAR(128),INTEGER,INTEGER,INTEGER,INTEGER,INTEGER,INTEGER,INTEGER,INTEGER,INTEGER,INTEGER,INTEGER,INTEGER,INTEGER,VARCHAR(64),VARCHAR(64),INTEGER,INTEGER,VARCHAR(50),UNIQUEIDENTIFIER,VARCHAR(50),VARCHAR(50),VARCHAR(50),VARCHAR(50),INTEGER,VARCHAR(129),VARCHAR(129),INTEGER,INTEGER,INTEGER,INTEGER,INTEGER,INTEGER,INTEGER,VARCHAR(50),INTEGER,VARCHAR(2048),VARCHAR(50),INTEGER,VARCHAR(32),INTEGER,INTEGER,INTEGER,INTEGER,INTEGER,INTEGER,VARCHAR(32),VARCHAR(50),VARCHAR(50),VARCHAR(64),VARCHAR(64),INTEGER,INTEGER,INTEGER,INTEGER,INTEGER,INTEGER,INTEGER,INTEGER,INTEGER,INTEGER,INTEGER,INTEGER,INTEGER,VARCHAR(32),INTEGER,VARCHAR(32),INTEGER,INTEGER,INTEGER,VARCHAR(50),VARCHAR(50),INTEGER,VARCHAR(50),VARCHAR(50),VARCHAR(50),VARCHAR(50),VARCHAR(50),VARCHAR(50),VARCHAR(50),VARCHAR(50),INTEGER,INTEGER,VARCHAR(255),VARCHAR(255),VARCHAR(255),VARCHAR(255),VARCHAR(50),VARCHAR(50),VARCHAR(129),VARCHAR(129),INTEGER,INTEGER,INTEGER,VARCHAR(50),VARCHAR(50),VARCHAR(50),VARCHAR(50)
1,1,17648,29473318,1446356796,1,29473318,186520748,"94936229","",0,1,4,0,0,0,0,0,0,0,0,0,0,"0","0",29473319,0,0,0,"0010","0010","",0,0,4,0,0,0,0,0,0,0,0,0,0,"0","0",0,1446356796,"0010","c42a57b4-1365-4412-a520-f52e221824df","","","","",0,"STC-SIP-TRUNK01","",13,0,0,0,0,0,0,"StandAloneCluster",0,"","",0,"",2,0,0,0,0,0,"","","","172.20.30.11","",0,0,0,0,0,0,0,0,0,0,0,0,1,"BF99DCE57F9211E59F3AE89DA880154A",0,"",0,0,0,"","",2,"","","","","","","","",0,0,"","","","","","","","",0,0,0,"","","",""`

Thanks :+1:

**Comment by slashdoom** [comment]
Hi dhyeem.  Thanks for the feedback and cdr file.  It's been a while since I've looked at this script so bare with me...

I was actually able to import the attached cdr file into my own ES so I'm thinking it's not so much a problem with the parsing of the file itself as it is some kind of race condition.  Like the cdr was still being written when the parser tries to move it.  I've added a quick check to mod_cdr_main.py that I'm hoping will catch this and retry until free.  Let me know if it works any better.

Cheers!

**Comment by dhyeem** [comment]
Hi Slashdoom, 

i will test it and update you , but there is another issue also i notice it, when you parse to ES the file will consider a new file even if the file is parsed already ( the parser will not check with ES if it's new file or update).

Regards

**Comment by slashdoom** [comment]
Thanks again.  Indeed this check unfortunately doesn't exist right now but it's a good idea.  I've added this as a new enhancement issue.

**Comment by slashdoom** [comment]
Both issues hopefully resolved.  Note new options in mod_conf.py if pulling.

**Comment by dhyeem** [comment]
Good Day Slashdoom , i think it working like a charm , i have test with +9000 CDR and it's fine , but i notice something in the indices , it will indices as the date was imported to ES and also as the CDR time, 

https://drive.google.com/file/d/0B9ROIIXyHqDXVkJfU1ZZQXExaUk/view?usp=sharing 

is there is an optoin to indices to be like this:

cdr_StandAloneCluster_01_**YYYYMMDD**0231_4007 , 

other thing i see that it recognize the duplicate .. 

https://drive.google.com/file/d/0B9ROIIXyHqDXMEVGSm44WWRfdXM/view?usp=sharing

Regards,

**Comment by slashdoom** [comment]
Okay, few more tweaks...  Should build the index from the datetime of the cdr record now.  You can change the date format in the mod_conf.py file if you wish.
