### ISSUE TITLE
Bulk Indexing will issue timeout from ES

### ISSUE THREAD

**Issue by dhyeem** [slashdoom/cdr_parser#3]
good Day Slashdoom, 
i have test the script with the new function you added, it is great but i face some issue i want you to know about. i have test your script with almost 10,000 CDR and CMR, i face two issue: 
- High CPU and memory after reaching 3000 file, the CPU raised to be 100%.
- After a while the ES will issue timeout below you will find the log : 

> root@dcpelksap21:/home/dhyeem# curl localhost:9200
> {
>   "name" : "Baron Zemo",
>   "cluster_name" : "elasticsearch",
>   "version" : {
>     "number" : "2.3.3",
>     "build_hash" : "218bdf10790eef486ff2c41a3df5cfa32dadcfde",
>     "build_timestamp" : "2016-05-17T15:40:04Z",
>     "build_snapshot" : false,
>     "lucene_version" : "5.5.0"
>   },
>   "tagline" : "You Know, for Search"
> }
> root@dcpelksap21:/home/dhyeem# /opt/cdr_parser/init.d/cdr_parser start
> Starting server
> root@dcpelksap21:/home/dhyeem# started with pid 2411
> 2016-08-12 14:41:38,431 - cdr_parser started
> 2016-08-12 14:41:38,561 - src_file = /home/dhyeem/logs/cmr_StandAloneCluster_03_201602180657_65425
> 2016-08-12 14:41:38,561 - dest_file = /home/dhyeem/logs/archive/cmr_StandAloneCluster_03_201602180657_65425
> 2016-08-12 14:41:38,561 - es_type = cmr_StandAloneCluster_03_201602180657_65425
> 2016-08-12 14:41:38,846 - 0 documents found
> 2016-08-12 14:41:39,347 - CDR successfully moved to archive.
> 2016-08-12 14:41:39,348 - built es_index: cmr-2016.02.18
> Traceback (most recent call last):
>   File "/opt/cdr_parser/cdr_parser.py", line 63, in <module>
>     daemon_runner.do_action()
>   File "/usr/local/lib/python2.7/dist-packages/daemon/runner.py", line 267, in do_action
>     func(self)
>   File "/usr/local/lib/python2.7/dist-packages/daemon/runner.py", line 186, in _start
>     self.app.run()
>   File "/opt/cdr_parser/cdr_parser.py", line 39, in run
>     do_main_program()
>   File "/opt/cdr_parser/mod_cdr_main.py", line 257, in do_main_program
>     logger.debug(es.index(index=es_index,doc_type=es_type,body=es_body))
>   File "/usr/local/lib/python2.7/dist-packages/elasticsearch/client/utils.py", line 69, in _wrapped
>     return func(_args, params=params, *_kwargs)
>   File "/usr/local/lib/python2.7/dist-packages/elasticsearch/client/__init__.py", line 279, in index
>     _make_path(index, doc_type, id), params=params, body=body)
>   File "/usr/local/lib/python2.7/dist-packages/elasticsearch/transport.py", line 329, in perform_request
>     status, headers, data = connection.perform_request(method, url, params, body, ignore=ignore, timeout=timeout)
>   File "/usr/local/lib/python2.7/dist-packages/elasticsearch/connection/http_urllib3.py", line 102, in perform_request
>     raise ConnectionTimeout('TIMEOUT', str(e), e)
> elasticsearch.exceptions.ConnectionTimeout: ConnectionTimeout caused by - ReadTimeoutError(HTTPConnectionPool(host='localhost', port='9200'): Read timed out. (read timeout=10))
> ^C
> root@dcpelksap21:/home/dhyeem# /opt/cdr_parser/init.d/cdr_parser stop
> Stopping server
> Traceback (most recent call last):
>   File "/opt/cdr_parser/cdr_parser.py", line 63, in <module>
>     daemon_runner.do_action()
>   File "/usr/local/lib/python2.7/dist-packages/daemon/runner.py", line 267, in do_action
>     func(self)
>   File "/usr/local/lib/python2.7/dist-packages/daemon/runner.py", line 217, in _stop
>     raise error
> daemon.runner.DaemonRunnerStopFailureError: PID file '/var/run/cdr_parser.pid' not locked

Server info : 
Operating system:   Ubuntu Linux 16.04
Kernel and CPU:     Linux 4.4.0-31-generic on x86_64
Processor information:  Intel(R) Xeon(R) CPU E5-2640 0 @ 2.50GHz, 2 cores
RAM : 4GB 

Regards,

**Comment by slashdoom** [comment]
Interesting...  Is it the java/elasticsearch or the python/cdr_parser processes that are the eating up the CPU when it hits 100%?  Does the ES node look health beyond 3000 files?

I've added parameters that might make the script's ES connection more forgiving.  See those here:
https://github.com/slashdoom/cdr_parser/blob/master/mod_cdr_main.py#L43

You can modify as you see fit.

**Comment by dhyeem** [comment]
ES statistic while i'm running the new CDR_Parser from Marvel : 
https://drive.google.com/file/d/0B9ROIIXyHqDXdnpPdVVtSU5uTjQ/view?usp=sharing

also the ES logs and some logs and CDR whiten the issue happen and some after it's clear maybe it will helpful for you. I'm seeing some logs exception in ES logs, 

https://drive.google.com/open?id=0B9ROIIXyHqDXMUM1NS0yMTdFWnM

> dhyeem@dcpelksap21:~$ java -version
> java version "1.8.0_101"
> Java(TM) SE Runtime Environment (build 1.8.0_101-b13)
> Java HotSpot(TM) 64-Bit Server VM (build 25.101-b13, mixed mode)
> 
> dhyeem@dcpelksap21:~$  curl -XGET 'http://localhost:9200/_cluster/health?pretty=true'
> {
>   "cluster_name" : "elasticsearch",
>   "status" : "yellow",
>   "timed_out" : false,
>   "number_of_nodes" : 1,
>   "number_of_data_nodes" : 1,
>   "active_primary_shards" : 275,
>   "active_shards" : 275,
>   "relocating_shards" : 0,
>   "initializing_shards" : 0,
>   "unassigned_shards" : 275,
>   "delayed_unassigned_shards" : 0,
>   "number_of_pending_tasks" : 0,
>   "number_of_in_flight_fetch" : 0,
>   "task_max_waiting_in_queue_millis" : 0,
>   "active_shards_percent_as_number" : 50.0
> }
> dhyeem@dcpelksap21:~$ curl localhost:9200
> {
>   "name" : "Citizen V",
>   "cluster_name" : "elasticsearch",
>   "version" : {
>     "number" : "2.3.5",
>     "build_hash" : "90f439ff60a3c0f497f91663701e64ccd01edbb4",
>     "build_timestamp" : "2016-07-27T10:36:52Z",
>     "build_snapshot" : false,
>     "lucene_version" : "5.5.0"
>   },
>   "tagline" : "You Know, for Search"

Regards,

**Comment by slashdoom** [comment]
It looks like somehow the debug messages from the logging stream are getting mixed into the ES http stream.  I can't explain that...  But I might at least have a workaround if you want to try it out.  

Note that the mod_conf.py file has changed again.

**Comment by dhyeem** [comment]
Dear , i try with the new optoin you made , the same issue, this is the outbout.

> dhyeem@dcpelksap21:~$ started with pid 8147
> 2016-08-18 08:07:23,978 - cdr_parser started
> 2016-08-18 08:07:24,049 - src_file = /home/dhyeem/logs/cdr_StandAloneCluster_02_201512270623_70884
> 2016-08-18 08:07:24,049 - dest_file = /home/dhyeem/logs/archive/cdr_StandAloneCluster_02_201512270623_70884
> 2016-08-18 08:07:24,049 - es_type = cdr_StandAloneCluster_02_201512270623_70884
> 2016-08-18 08:07:24,376 - 0 documents found
> 2016-08-18 08:07:24,879 - CDR successfully moved to archive.
> 2016-08-18 08:07:24,881 - built es_index: cdr-2015.12.27
> Traceback (most recent call last):
>   File "/opt/cdr_parser/cdr_parser.py", line 63, in <module>
>     daemon_runner.do_action()
>   File "/usr/local/lib/python2.7/dist-packages/daemon/runner.py", line 267, in do_action
>     func(self)
>   File "/usr/local/lib/python2.7/dist-packages/daemon/runner.py", line 186, in _start
>     self.app.run()
>   File "/opt/cdr_parser/cdr_parser.py", line 39, in run
>     do_main_program()
>   File "/opt/cdr_parser/mod_cdr_main.py", line 257, in do_main_program
>     logger.debug(es.index(index=es_index,doc_type=es_type,body=es_body))
>   File "/usr/local/lib/python2.7/dist-packages/elasticsearch/client/utils.py", line 69, in _wrapped
>     return func(_args, params=params, *_kwargs)
>   File "/usr/local/lib/python2.7/dist-packages/elasticsearch/client/__init__.py", line 279, in index
>     _make_path(index, doc_type, id), params=params, body=body)
>   File "/usr/local/lib/python2.7/dist-packages/elasticsearch/transport.py", line 329, in perform_request
>     status, headers, data = connection.perform_request(method, url, params, body, ignore=ignore, timeout=timeout)
>   File "/usr/local/lib/python2.7/dist-packages/elasticsearch/connection/http_urllib3.py", line 102, in perform_request
>     raise ConnectionTimeout('TIMEOUT', str(e), e)
> elasticsearch.exceptions.ConnectionTimeout: ConnectionTimeout caused by - ReadTimeoutError(HTTPConnectionPool(host='localhost', port='9200'): Read timed out. (read timeout=10))

regards :+1:

**Comment by slashdoom** [comment]
I would have expected to see: Read timed out. (read timeout=**30**))

Since we set the connection timeout to 30s on the latest at:
https://github.com/slashdoom/cdr_parser/blob/master/mod_cdr_main.py#L26

Unfortunately, I think what's it's telling us is that the script couldn't complete its ES read/write task within the timeout period.  I haven't been able to produce this on a healthy ES cluster.  On an red status ES that's too full to assign shards I get the same error.
